import streamlit as st
import json
import os
from datetime import datetime
import random
import base64
from fpdf import FPDF
import time

st.set_page_config(page_title="Public Complaint Box", page_icon="📮", layout="wide")

# Files
COMPLAINT_FILE = "complaints.json"
ADMIN_PASS = "Admin@2024"

# Session
if 'admin_login' not in st.session_state:
    st.session_state.admin_login = False
if 'complaint_done' not in st.session_state:
    st.session_state.complaint_done = False

# ============ FUNCTIONS ============

def generate_id():
    now = datetime.now()
    return f"PUB-{now.strftime('%Y%m%d')}-{random.randint(1000,9999)}"

def save_complaint(data):
    try:
        all_data = {}
        if os.path.exists(COMPLAINT_FILE):
            with open(COMPLAINT_FILE, 'r') as f:
                all_data = json.load(f)
        
        complaint_id = generate_id()
        
        all_data[complaint_id] = {
            **data,
            "id": complaint_id,
            "date": datetime.now().strftime("%Y-%m-%d"),
            "time": datetime.now().strftime("%I:%M %p"),
            "status": "Pending"
        }
        
        with open(COMPLAINT_FILE, 'w') as f:
            json.dump(all_data, f, indent=2)
        
        return complaint_id
    except:
        return None

def load_complaints():
    if os.path.exists(COMPLAINT_FILE):
        with open(COMPLAINT_FILE, 'r') as f:
            return json.load(f)
    return {}

def update_status(cid, status):
    data = load_complaints()
    if cid in data:
        data[cid]['status'] = status
        with open(COMPLAINT_FILE, 'w') as f:
            json.dump(data, f)
        return True
    return False

def delete_complaint(cid):
    data = load_complaints()
    if cid in data:
        del data[cid]
        with open(COMPLAINT_FILE, 'w') as f:
            json.dump(data, f)
        return True
    return False

def create_pdf(cid, data):
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_fill_color(33, 150, 243)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 22)
    pdf.cell(0, 18, 'PUBLIC COMPLAINT REPORT', 0, 1, 'C', True)
    pdf.ln(8)
    
    # Complaint ID Box
    pdf.set_fill_color(255, 243, 224)
    pdf.set_text_color(230, 81, 0)
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 12, f"ID: {cid}", 0, 1, 'C', True)
    pdf.ln(8)
    
    # Status
    pdf.set_text_color(0, 0, 0)
    status_colors = {
        "Pending": (255, 152, 0),
        "In Progress": (33, 150, 243),
        "Resolved": (76, 175, 80),
        "Rejected": (244, 67, 54)
    }
    
    if data['status'] in status_colors:
        r, g, b = status_colors[data['status']]
        pdf.set_text_color(r, g, b)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, f"Status: {data['status']}", 0, 1)
    pdf.ln(5)
    
    # Line
    pdf.set_draw_color(33, 150, 243)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(8)
    
    # Details Section
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', 'B', 13)
    pdf.set_fill_color(232, 245, 253)
    pdf.cell(0, 10, '  PERSONAL INFORMATION', 0, 1, 'L', True)
    pdf.ln(5)
    
    fields = [
        ("Name", data['name']),
        ("Phone", data['phone']),
        ("Email", data.get('email', 'Not provided')),
        ("City", data.get('city', 'Not provided')),
        ("Date", f"{data['date']} at {data['time']}"),
        ("Priority", data['priority']),
        ("Category", data['category']),
        ("Subject", data['subject']),
    ]
    
    for label, value in fields:
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(35, 9, f"  {label}:", 0, 0)
        pdf.set_font('Arial', '', 11)
        pdf.cell(0, 9, str(value), 0, 1)
    
    pdf.ln(5)
    
    # Description
    pdf.set_font('Arial', 'B', 13)
    pdf.set_fill_color(232, 245, 253)
    pdf.cell(0, 10, '  COMPLAINT DESCRIPTION', 0, 1, 'L', True)
    pdf.ln(5)
    
    pdf.set_font('Arial', '', 11)
    pdf.set_x(15)
    pdf.multi_cell(180, 8, data['description'])
    
    pdf.ln(10)
    
    # Footer
    pdf.set_draw_color(33, 150, 243)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_font('Arial', 'I', 9)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 8, 'Confidential Document - Generated by Public Complaint System', 0, 1, 'C')
    pdf.cell(0, 8, f'Printed: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}', 0, 1, 'C')
    
    return pdf.output(dest='S').encode('latin-1')

def download_link(pdf_bytes, filename):
    b64 = base64.b64encode(pdf_bytes).decode()
    return f'''
    <a href="data:application/pdf;base64,{b64}" 
       download="{filename}"
       style="background:#2196F3;color:white;padding:12px 25px;
              text-decoration:none;border-radius:8px;display:inline-block;">
        📥 Download PDF
    </a>
    '''

# ============ MAIN UI ============

# Custom CSS
st.markdown("""
<style>
    .big-title {
        font-size: 50px;
        text-align: center;
        font-weight: bold;
        color: #1565C0;
    }
    .subtitle {
        text-align: center;
        font-size: 18px;
        color: #666;
    }
    .success-box {
        background: linear-gradient(135deg, #11998e, #38ef7d);
        padding: 30px;
        border-radius: 15px;
        color: white;
        text-align: center;
    }
    .complaint-card {
        border-left: 5px solid #2196F3;
        padding: 15px;
        margin: 10px 0;
        background: #f9f9f9;
        border-radius: 5px;
    }
</style>
""", unsafe_allow_html=True)

# Header
st.markdown('<p class="big-title">📮 PUBLIC COMPLAINT BOX</p>', unsafe_allow_html=True)
st.markdown('<p class="subtitle">Your Voice Matters - Submit Any Complaint</p>', unsafe_allow_html=True)
st.markdown("---")

# Tabs
tab1, tab2, tab3 = st.tabs(["📝 Submit Complaint", "🔐 Admin Panel", "🔍 Track Status"])

# ============ TAB 1: SUBMIT COMPLAINT ============
with tab1:
    
    if st.session_state.complaint_done:
        st.markdown(f"""
        <div class="success-box">
            <h1>✅ Complaint Submitted!</h1>
            <h2>Your Reference ID:</h2>
            <h1 style="font-size:40px;letter-spacing:3px;">{st.session_state.complaint_done}</h1>
            <p>Save this ID to track your complaint</p>
            <p style="font-size:12px;">We will review your complaint within 48 hours</p>
        </div>
        """, unsafe_allow_html=True)
        
        st.markdown("<br>", unsafe_allow_html=True)
        if st.button("📝 Submit Another Complaint", use_container_width=True, type="primary"):
            st.session_state.complaint_done = False
            st.rerun()
    
    else:
        st.markdown("### 📋 Complaint Form")
        st.markdown("*All fields marked with * are required*")
        
        with st.form("public_complaint"):
            
            # Personal Info
            st.markdown("#### 👤 Your Information")
            col1, col2 = st.columns(2)
            
            with col1:
                name = st.text_input("Full Name *", placeholder="Enter your name")
                phone = st.text_input("Phone Number *", placeholder="+92 300 1234567")
                city = st.text_input("City", placeholder="Karachi, Lahore, etc.")
            
            with col2:
                email = st.text_input("Email Address", placeholder="your@email.com")
                priority = st.selectbox("Priority *", ["Medium", "Low", "High", "Urgent"])
            
            st.markdown("---")
            
            # Complaint Details
            st.markdown("#### 📝 Complaint Details")
            
            category = st.selectbox("Category *", [
                "Select Category...",
                "Security Issue",
                "Corruption Report",
                "Harassment",
                "Safety Concern",
                "Fraud Report",
                "Abuse of Power",
                "Discrimination",
                "Property Dispute",
                "Cyber Crime",
                "Other"
            ])
            
            subject = st.text_input("Subject *", placeholder="Brief title of your complaint")
            
            description = st.text_area(
                "Detailed Description *",
                height=180,
                placeholder="Please describe your complaint in detail...\n\nWhen did it happen?\nWhere did it happen?\nWho was involved?\nAny evidence?"
            )
            
            st.markdown("---")
            
            # Terms
            agree = st.checkbox("I confirm that the information provided is true and accurate *")
            
            submitted = st.form_submit_button("📤 SUBMIT COMPLAINT", type="primary", use_container_width=True)
            
            if submitted:
                if not name:
                    st.error("❌ Please enter your name")
                elif not phone:
                    st.error("❌ Please enter your phone number")
                elif category == "Select Category...":
                    st.error("❌ Please select a category")
                elif not subject:
                    st.error("❌ Please enter a subject")
                elif not description:
                    st.error("❌ Please write your complaint description")
                elif not agree:
                    st.error("❌ Please confirm the information is true")
                else:
                    data = {
                        "name": name,
                        "phone": phone,
                        "email": email,
                        "city": city,
                        "priority": priority,
                        "category": category,
                        "subject": subject,
                        "description": description
                    }
                    
                    cid = save_complaint(data)
                    if cid:
                        st.session_state.complaint_done = cid
                        st.rerun()
                    else:
                        st.error("❌ Error submitting complaint. Please try again.")

# ============ TAB 2: ADMIN PANEL ============
with tab2:
    
    if not st.session_state.admin_login:
        st.markdown("### 🔐 Admin Login")
        st.markdown("Only authorized personnel can access")
        
        pwd = st.text_input("Enter Password:", type="password")
        if st.button("🔑 Login", use_container_width=True):
            if pwd == ADMIN_PASS:
                st.session_state.admin_login = True
                st.rerun()
            else:
                st.error("❌ Access Denied!")
    else:
        st.success("✅ Admin Access Granted")
        
        col1, col2 = st.columns([3, 1])
        with col2:
            if st.button("🚪 Logout", use_container_width=True):
                st.session_state.admin_login = False
                st.rerun()
        
        st.markdown("---")
        
        complaints = load_complaints()
        
        if complaints:
            # Stats
            total = len(complaints)
            pending = sum(1 for c in complaints.values() if c['status'] == 'Pending')
            progress = sum(1 for c in complaints.values() if c['status'] == 'In Progress')
            resolved = sum(1 for c in complaints.values() if c['status'] == 'Resolved')
            
            col1, col2, col3, col4 = st.columns(4)
            with col1:
                st.metric("📊 Total", total)
            with col2:
                st.metric("⏳ Pending", pending)
            with col3:
                st.metric("🔄 In Progress", progress)
            with col4:
                st.metric("✅ Resolved", resolved)
            
            st.markdown("---")
            
            # Filters
            col1, col2 = st.columns(2)
            with col1:
                filter_status = st.selectbox("Filter Status:", ["All", "Pending", "In Progress", "Resolved"])
            with col2:
                search = st.text_input("🔍 Search by Name/ID/Subject")
            
            st.markdown("---")
            
            # Display complaints
            for cid, data in reversed(list(complaints.items())):
                
                # Apply filters
                if filter_status != "All" and data['status'] != filter_status:
                    continue
                
                if search and search.lower() not in cid.lower() and search.lower() not in data['name'].lower() and search.lower() not in data['subject'].lower():
                    continue
                
                # Status colors
                status_info = {
                    "Pending": ("🟠", "#ff9800"),
                    "In Progress": ("🔵", "#2196F3"),
                    "Resolved": ("🟢", "#4CAF50"),
                    "Rejected": ("🔴", "#f44336")
                }
                icon, color = status_info.get(data['status'], ("⚪", "#999"))
                
                with st.expander(f"{icon} {data['subject']} | {data['name']} | {data['date']}"):
                    
                    col1, col2 = st.columns([3, 1])
                    
                    with col1:
                        st.markdown(f"""
                        **ID:** {cid}  
                        **Name:** {data['name']}  
                        **Phone:** {data['phone']}  
                        **Email:** {data.get('email', 'N/A')}  
                        **City:** {data.get('city', 'N/A')}  
                        **Category:** {data['category']}  
                        **Priority:** {data['priority']}  
                        **Date:** {data['date']} at {data['time']}
                        """)
                        
                        with st.expander("📄 View Full Description"):
                            st.write(data['description'])
                    
                    with col2:
                        # Status update
                        new_status = st.selectbox(
                            "Update Status",
                            ["Pending", "In Progress", "Resolved", "Rejected"],
                            key=f"st_{cid}"
                        )
                        
                        if st.button("📝 Update", key=f"up_{cid}", use_container_width=True):
                            update_status(cid, new_status)
                            st.success("Updated!")
                            st.rerun()
                        
                        # PDF Download
                        pdf_bytes = create_pdf(cid, {**data, "status": new_status})
                        st.markdown(download_link(pdf_bytes, f"Complaint_{cid}.pdf"), unsafe_allow_html=True)
                        
                        # Delete
                        if st.button("🗑️ Delete", key=f"del_{cid}", use_container_width=True):
                            delete_complaint(cid)
                            st.warning("Deleted!")
                            st.rerun()
        else:
            st.info("📭 No complaints received yet")

# ============ TAB 3: TRACK STATUS ============
with tab3:
    st.markdown("### 🔍 Track Your Complaint Status")
    st.markdown("Enter the Reference ID you received when submitting your complaint")
    
    track_id = st.text_input("Enter Complaint ID:", placeholder="PUB-20240101-1234")
    
    if st.button("🔍 Check Status", use_container_width=True, type="primary"):
        if track_id:
            complaints = load_complaints()
            
            if track_id in complaints:
                data = complaints[track_id]
                
                status_colors = {
                    "Pending": ("🟠 Pending", "#ff9800", "Your complaint is under review"),
                    "In Progress": ("🔵 In Progress", "#2196F3", "We are working on your complaint"),
                    "Resolved": ("🟢 Resolved", "#4CAF50", "Your complaint has been resolved"),
                    "Rejected": ("🔴 Rejected", "#f44336", "Your complaint was not accepted")
                }
                
                status_text, color, message = status_colors.get(
                    data['status'], 
                    ("Unknown", "#999", "Status unknown")
                )
                
                st.markdown(f"""
                <div style="border: 2px solid {color}; border-radius: 10px; padding: 20px; background: #f9f9f9;">
                    <h2 style="color: {color};">{status_text}</h2>
                    <p style="font-size: 18px;">{message}</p>
                    <hr>
                    <p><b>Complaint ID:</b> {track_id}</p>
                    <p><b>Subject:</b> {data['subject']}</p>
                    <p><b>Submitted:</b> {data['date']} at {data['time']}</p>
                    <p><b>Category:</b> {data['category']}</p>
                    <p><b>Priority:</b> {data['priority']}</p>
                </div>
                """, unsafe_allow_html=True)
            else:
                st.error("❌ Complaint ID not found. Please check and try again.")
        else:
            st.warning("⚠️ Please enter a Complaint ID")

# Footer
st.markdown("---")
st.markdown("""
<div style="text-align:center; color:gray; padding:20px;">
    <p>📮 Public Complaint Box | Your Voice Matters</p>
    <p style="font-size:12px;">All complaints are confidential and secure</p>
    <p style="font-size:10px;">© 2024 Public Complaint System</p>
</div>
""", unsafe_allow_html=True)
